// Generated by tools/gen_eyes.py - do not edit.
#pragma once
#include "lvgl.h"

#define EYE_W 88
#define EYE_H 150
#define IRIS_D 50

extern const lv_image_dsc_t img_eye_sclera;
extern const lv_image_dsc_t img_iris_idle;
extern const lv_image_dsc_t img_iris_listening;
extern const lv_image_dsc_t img_iris_thinking;
extern const lv_image_dsc_t img_iris_speaking;
extern const lv_image_dsc_t img_iris_connecting;
extern const lv_image_dsc_t img_iris_error;
extern const lv_image_dsc_t img_iris_boot;
