// Generated by tools/gen_images.py - do not edit.
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t img_title;  // AI ลูกเทพ
extern const lv_image_dsc_t img_scan_ap;  // สแกน QR เพื่อเชื่อมต่อบอร์ด
extern const lv_image_dsc_t img_scan_setup;  // สแกนอีกครั้งเพื่อตั้งค่า Wi-Fi
extern const lv_image_dsc_t img_connecting;  // กำลังเชื่อมต่อ Wi-Fi...
extern const lv_image_dsc_t img_connected;  // เชื่อมต่อ Wi-Fi แล้ว
extern const lv_image_dsc_t img_failed;  // เชื่อมต่อไม่สำเร็จ
extern const lv_image_dsc_t img_testing;  // กำลังทดสอบการเชื่อมต่อ...
extern const lv_image_dsc_t img_reset;  // ล้างค่า Wi-Fi แล้ว
extern const lv_image_dsc_t img_wifi_lost;  // Wi-Fi หลุด กำลังต่อใหม่
extern const lv_image_dsc_t img_updating;  // กำลังอัปเดตเฟิร์มแวร์
extern const lv_image_dsc_t img_update_done;  // อัปเดตสำเร็จ กำลังรีสตาร์ท
