#!/usr/bin/env python3
"""Render Thai UI strings to LVGL 9 A8 images -> main/img_text.c + main/img_text.h.

LVGL's built-in fonts have no Thai glyphs; Phase 7 replaces these with a proper
Noto Sans Thai LVGL font. Needs pillow + macOS Thonburi.   Usage: python tools/gen_images.py
"""
from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/Thonburi.ttc"
# symbol -> (text, size)
STRINGS = {
    "img_title":       ("AI ลูกเทพ", 34),
    "img_scan_ap":     ("สแกน QR เพื่อเชื่อมต่อบอร์ด", 20),
    "img_scan_setup":  ("สแกนอีกครั้งเพื่อตั้งค่า Wi-Fi", 20),
    "img_connecting":  ("กำลังเชื่อมต่อ Wi-Fi...", 20),
    "img_connected":   ("เชื่อมต่อ Wi-Fi แล้ว", 20),
    "img_failed":      ("เชื่อมต่อไม่สำเร็จ", 20),
    "img_testing":     ("กำลังทดสอบการเชื่อมต่อ...", 20),
    "img_reset":       ("ล้างค่า Wi-Fi แล้ว", 20),
    "img_wifi_lost":   ("Wi-Fi หลุด กำลังต่อใหม่", 20),
    "img_updating":    ("กำลังอัปเดตเฟิร์มแวร์", 20),
    "img_update_done": ("อัปเดตสำเร็จ กำลังรีสตาร์ท", 20),
}

c_out = ['// Generated by tools/gen_images.py - do not edit.', '#include "img_text.h"', ""]
h_out = ['// Generated by tools/gen_images.py - do not edit.', "#pragma once", '#include "lvgl.h"', ""]
for sym, (text, size) in STRINGS.items():
    font = ImageFont.truetype(FONT, size)
    l, t, r, b = font.getbbox(text)
    w, h = r - l + 4, b - t + 4
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-l + 2, -t + 2), text, font=font, fill=255)
    data = img.tobytes()
    rows = ["    " + ",".join(f"0x{v:02x}" for v in data[i:i + 20]) + "," for i in range(0, len(data), 20)]
    c_out += [f"// {text}  ({w}x{h})", f"static const uint8_t {sym}_map[] = {{", *rows, "};",
              f"const lv_image_dsc_t {sym} = {{",
              "    .header.magic = LV_IMAGE_HEADER_MAGIC,", "    .header.cf = LV_COLOR_FORMAT_A8,",
              f"    .header.w = {w},", f"    .header.h = {h},", f"    .header.stride = {w},",
              f"    .data_size = sizeof({sym}_map),", f"    .data = {sym}_map,", "};", ""]
    h_out.append(f"extern const lv_image_dsc_t {sym};  // {text}")
    print(f"{sym}: {w}x{h}")
open("main/img_text.c", "w").write("\n".join(c_out))
open("main/img_text.h", "w").write("\n".join(h_out) + "\n")
