#!/usr/bin/env python3
"""Render Thai UI strings to 1-bit bitmaps -> src/thai_text.h (LovyanGFX drawBitmap format).

Usage: python tools/gen_thai_text.py [--preview out.png]
Needs: pillow. Uses a Thai font installed on macOS (Thonburi).
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/Thonburi.ttc"
# name -> (text, font size)
STRINGS = {
    "TH_TITLE":      ("AI ลูกเทพ", 34),
    "TH_SCAN_AP":    ("สแกน QR เพื่อเชื่อมต่อบอร์ด", 20),
    "TH_SCAN_SETUP": ("สแกนอีกครั้งเพื่อตั้งค่า Wi-Fi", 20),
    "TH_CONNECTING": ("กำลังเชื่อมต่อ Wi-Fi...", 22),
    "TH_CONNECTED":  ("เชื่อมต่อ Wi-Fi แล้ว", 22),
    "TH_FAILED":     ("เชื่อมต่อไม่สำเร็จ", 22),
    "TH_RESET":      ("ล้างค่า Wi-Fi แล้ว", 22),
}

def render(text, size):
    font = ImageFont.truetype(FONT, size)
    l, t, r, b = font.getbbox(text)
    w, h = r - l + 2, b - t + 2
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-l + 1, -t + 1), text, font=font, fill=255)
    return img.point(lambda p: 255 if p > 110 else 0, "1")

def main():
    out = ["// Generated by tools/gen_thai_text.py - do not edit.", "#pragma once", "#include <stdint.h>", ""]
    sheet = []
    for name, (text, size) in STRINGS.items():
        img = render(text, size)
        w, h = img.size
        rb = (w + 7) // 8
        data = img.tobytes()  # 1-bit, MSB first, rows padded to bytes
        out.append(f"// {text}")
        out.append(f"constexpr int {name}_W = {w}, {name}_H = {h};")
        out.append(f"static const uint8_t {name}[] = {{")
        for i in range(0, len(data), 16):
            out.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",")
        out.append("};\n")
        sheet.append(img.convert("L"))
        print(f"{name}: {w}x{h}", file=sys.stderr)
    open("src/thai_text.h", "w").write("\n".join(out))
    if "--preview" in sys.argv:
        path = sys.argv[sys.argv.index("--preview") + 1]
        H = sum(i.size[1] + 8 for i in sheet)
        canvas = Image.new("L", (300, H), 0)
        y = 4
        for i in sheet:
            canvas.paste(i, (4, y)); y += i.size[1] + 8
        canvas.resize((600, H * 2), Image.NEAREST).save(path)

main()
